export default {
  title: "Create Next App",
  description: "Generated by create next app",
  nav: {
    docs: "Read our docs",
    deploy: "Deploy now"
  },
  hello: "Hello",
  appName: "My App",
  languages: {
    en: "English",
    ar: "عربي"
  },
  dashboard: "Dashboard"
}; 