import { Geist } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ThemeProvider } from 'next-themes';

const geist = Geist({
  subsets: ["latin", "arabic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html suppressHydrationWarning>
      <body className={geist.className}>
        <ThemeProvider 
          attribute="class" 
          defaultTheme="system" 
          enableSystem={true}
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

function LanguageSwitcher({ currentLocale }) {
  return (
    <div className="fixed top-4 right-4 flex gap-2">
      <Link href="/" locale="en" className={currentLocale === 'en' ? 'font-bold' : ''}>
        EN
      </Link>
      <Link href="/" locale="ar" className={currentLocale === 'ar' ? 'font-bold' : ''}>
        عربي
      </Link>
    </div>
  );
}
